[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = "0.8.19"
optimizer = true
optimizer_runs = 1_000_000
verbosity=3
libraries = [
	"src/libraries/ChainopolyBoard.sol:ChainopolyBoard:0x5FbDB2315678afecb367f032d93F642f64180aa3",
	"src/libraries/ChainopolyCore.sol:ChainopolyCore:0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
	"src/libraries/ChainopolyCards.sol:ChainopolyCards:0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
	"src/libraries/ChainopolyHelpers.sol:ChainopolyHelpers:0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
	"src/libraries/Chainopoly.sol:Chainopoly:0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
]
remappings = [
	"@openzeppelin/=lib/openzeppelin-contracts/",
	# "@chainlink/=lib/contracts-ccip/src/v0.8/",
	# "@api3/=node_modules/@api3/airnode-protocol",
	# "@api3/=lib/airnode/packages",
	"forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config